### PR TITLE
Use Unix domain sockets on Windows as a control channel for all the reactors

### PR DESCRIPTION
**Pull request by smtrfnv**
**Describe your changes**
`ntcs::Controller` now by default uses Unux domain sockets for internal communication on Windows platform. If UDS pair cannot be created then it falls back to TCP based implementation.

**Testing performed**
Some tests were added to `ntcs_controlchannel.t`, they check basic scenario and fallback scenario.

**Additional context**
It was decided to not touch `ntsb::Controller` implementation. This PR depends on https://github.com/bloomberg/ntf-core/pull/89  and assume to be merged afterwards

### CODE REVIEW

**Comment by smtrfnv** [comment]
@mattrm456 what should we do with
```
bool AdapterUtil::supportsLocalDatagram()
```
? On Windows it currently returns false.

**Comment by mattrm456** [comment]
Windows does not support Unix domain datagram sockets, only Unix domain stream sockets.

**Review by mattrm456 — CHANGES_REQUESTED** [review]
Fallback to TCP on Unix when UDS control channels are unavailable, and do not log at the "fatal" severity in `initUdsPair`.

**Comment by mattrm456** [comment]
Also set TCP keep-alive socket option on TCP control channels.

**Comment by smtrfnv** [comment]
> Also set TCP keep-alive socket option on TCP control channels.

Done.


> Fallback to TCP on Unix when UDS control channels are unavailable, and do not log at the "fatal" severity in `initUdsPair`.

Done,. Though it is not really possible to test for all the platforms.

**Pull request merged**
